#Cargando mis archivos 
#
source = ~/.config/hypr/My_WindowsRules.conf
source = ~/.config/hypr/Ny_Startup_Apps.conf
source = ~/.config/hypr/UserKeybinds.conf
#exec-once = /home/misArchivos/Documentos/Scripts_Linux/usb-sound-watcher.sh
