
#Mis windowrule
#
#Reglas Para Waydroid
#windowrulev2 = fullscreen on, class:^(Waydroid)$
# Hacer que Waydroid se abra siempre fullscreen
#windowrulev2 = match:class Waydroid, fullscreen on, maximize on
windowrule = match:class Waydroid, fullscreen_state 2  #Esto me ayudo a poner waydroid en fullscreen
windowrule = match:class Waydroid, no_blur on

#windowrulev2 = fullscreen_state 2, title:^(.*Waydroid.*)$
#windowrule = nogaps, class:Waydroid
#windowrule = noborder, class:Waydroid
#windowrule = nofocusborder, class:Waydroid


#Reglas para VSCode

#windowrule = tag +visualcode, class:^([Cc]ode)$
#windowrule = opacity 0.95 0.85, tag:visualcode*
